### ISSUE TITLE
The p311 builds have python<=3.11 set

### ISSUE THREAD

**Issue by corby** [embedded-community/pc-ble-driver-py#16]
The artifacts in the v0.17.5 release for 3.11 are clamped to 3.7>,<=3.11 which means pip won't install them for 3.11.* (i.e. 3.11.1)
Please update setup.py

```
diff --git a/setup.py b/setup.py
index 73b3501..a8b58e3 100644
--- a/setup.py
+++ b/setup.py
@@ -102,7 +102,7 @@ setup(
     ],
     keywords="nordic nrf51 nrf52 ble bluetooth softdevice serialization bindings pc-ble-driver pc-ble-driver-py "
     "pc_ble_driver pc_ble_driver_py",
-    python_requires=">3.7, <=3.11",
+    python_requires=">3.7, <3.12",
     install_requires=requirements,
     packages=packages,
     package_data={
```

**Comment by jupe** [comment]
good catch. Can you open PR for it?

**Comment by sw** [comment]
It's unfortunate that Nordic seems to have abandoned that package (the upstream is now archived).

As mentioned in NordicSemiconductor/pc-ble-driver-py/issues/230, it would be great if this package could support the upcoming Python 3.13. I don't think there are large modifications required but I'm not knowledgeable enough with the build and packaging system to offer a clean PR.

**Comment by jupe** [comment]
Latest release should fix this case.
